#!/bin/bash

VOLUME="$1"
TARBALL="$2"

usage() {
  echo "Usage: ./backup <volume> <tarball>"
  exit 1
}

if [ -z "$VOLUME" ]; then
    echo "Error: No volume supplied."
    usage
elif [ -z "$TARBALL" ]; then
    echo "Error: No tarball supplied."
    usage
elif [ ! "$( docker volume inspect -f '{{.Name}}' $VOLUME 2>/dev/null )" == "$VOLUME" ]; then
    echo "Error: Volume '$VOLUME' not found."
    usage
else
    DIR=$(dirname "$TARBALL")
    FILENAME=$(basename "$TARBALL")

    if [ "$DIR" == "." ]; then
        DIR=$(pwd)
    fi

    docker run --rm \
                -v "$VOLUME":/from \
                -v "$DIR":/to \
                debian \
                /bin/sh -c " \
                cd /from && \
                /bin/tar cf /to/$FILENAME ."
    echo "Success! Volume '$VOLUME' has been backed up to '$TARBALL'."
fi
