#!/bin/bash

TARBALL="$1"
VOLUME="$2"

usage() {
  echo "Usage: ./restore <tarball> <volume>"
  exit 1
}

if [ -z "$TARBALL" ]; then
    echo "Error: No tarball supplied."
    usage
elif [ -z "$VOLUME" ]; then
    echo "Error: No volume supplied."
    usage
elif [ ! -f "$TARBALL" ]; then
    echo "Error: Tarball '$TARBALL' not found."
    usage
else
    if [ ! "$( docker volume inspect -f '{{.Name}}' $VOLUME 2>/dev/null )" == "$VOLUME" ]; then
        docker volume create --name $VOLUME > /dev/null 2>&1
    fi

    DIR=$(dirname "$TARBALL")
    FILENAME=$(basename "$TARBALL")

    if [ "$DIR" == "." ]; then
        DIR=$(pwd)
    fi

    docker run --rm \
                -v "$DIR":/from \
                -v "$VOLUME":/to \
                debian \
                /bin/sh -c " \
                cd /to && \
                /bin/tar xf /from/$FILENAME"
    echo "Success! Tarball '$TARBALL' has been restored to volume '$VOLUME'."
fi
